name: Build and Test on Windows

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install MSYS2
        run: choco install msys2

      - name: Setup MSYS2
        shell: msys2 {0}
        run: |
          pacman -Syu --noconfirm
          pacman -Syu --noconfirm
          pacman -S mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-SDL2_ttf --noconfirm

      - name: Add MSYS2 to PATH
        run: echo "C:\tools\msys64\mingw64\bin" >> $GITHUB_PATH

      - name: Verify SDL2 Installation
        shell: cmd
        run: |
          dir C:\tools\msys64\mingw64\include\SDL2
          dir C:\tools\msys64\mingw64\lib

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Install Dependencies
        shell: msys2 {0}
        run: |
          cd player
          go mod tidy

      - name: Verify Go Environment
        run: go env

      - name: Verify Compiler
        run: |
          gcc --version
          g++ --version

      - name: Verify Environment Variables
        run: |
          echo "CGO_CFLAGS: $env:CGO_CFLAGS"
          echo "CGO_LDFLAGS: $env:CGO_LDFLAGS"

      - name: Build Package
        env:
          CGO_CFLAGS: "-IC:/tools/msys64/mingw64/include/SDL2"
          CGO_LDFLAGS: "-LC:/tools/msys64/mingw64/lib"
        shell: msys2 {0}
        run: |
          mkdir -p ../JukaGUI-Trimui-Windows
          cd player
          echo "CGO_CFLAGS: $env:CGO_CFLAGS"
          echo "CGO_LDFLAGS: $env:CGO_LDFLAGS"
          go build -o ../JukaGUI-Trimui-Windows/JukaGUI.exe ./
          echo "Build completed."
